language: objective-c

before_install:
- git submodule update --init --recursive
- gem install cocoapods

- pod --version
- pod setup --silent
- pod repo update --silent

#check podspec
- pod spec lint ShareKit.podspec

#check podspec with current commit
- pod lib lint ShareKit.podspec

script:

#build library
- xctool -project "ShareKit.xcodeproj" -scheme "Static Library" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

#run tests
- xctool test -project "ShareKit.xcodeproj" -scheme "Static Library" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

